
[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "Buttonless"
opacity = 0.90

[window.padding]
x = 16
y = 16

[[keyboard.bindings]]
key = "Key1"
mods = "Command"
action = "IncreaseFontSize"

[general]
live_config_reload = true
import = [
   "~/.config/alacritty/alacritty-dark.toml"
]

