#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
dry="0"

while [[ $# -gt 0 ]]; do
  if [[ $1 == "--help" || $1 == "-h" ]]; then
    echo "usage: use \`dev-env\` to replace all dotfiles."
    echo "       use \`dev-env <filter-query>\` to only replace dotfiles whose name contains the given string"
    echo "       use \`dev-env dry <filter-query>\` to dry run the replacement"
    exit 0
  elif  [[ $1 == "dry" ]]; then
    dry="1"
  else
    filter="$1"
    break
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "execute $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  "$@"
}

copy() {
  from=$1
  to=$2

  log "-------- Copying from $from --------"
  pushd $from > /dev/null
  # ignore hidden files/dirs
  files=$(find . -mindepth 2 -maxdepth 2 ! -path "./.*/*" ! -path "*/.DS_Store")
  for file in $files; do
    if [[ $file != *"$filter"* ]]; then
      log "ignoring $file"
      continue
    fi
    # if the directory already exists, we copy it into it
    if [[ -d $file ]]; then
      base=$(basename $file) 
      execute cp -r $file/ $to/$base
    else
      execute cp $file $to
    fi
  done
  popd > /dev/null
  log "-------- End copying --------"
}

source $script_dir/lib/os.sh

case $OS in
  "macos") os_dir=$script_dir/macos ;;
  "wsl")   os_dir=$script_dir/wsl ;;
  *) 
    log "Unsupported platform (need macOS or WSL)"
    exit 1
esac

common=$script_dir/common

log "$script_dir -- os: $OS -- filter: $filter"

copy $common $HOME
copy $os_dir $HOME
