require("wysstobi")
vim.lsp.enable('frege')
vim.lsp.enable('ts_ls')
vim.lsp.enable('lua_ls')
vim.lsp.enable('tinymist')
vim.lsp.enable('hls')
vim.lsp.enable('rust_analyzer')
vim.lsp.enable('pylsp')
vim.lsp.enable('djls')
vim.lsp.enable('marksman')
vim.lsp.enable("astro")

